### ISSUE TITLE
Incorrect national number result when dealing with certain phone number format input (ID)

### ISSUE THREAD

**Issue by amakmurr** [nyaruka/phonenumbers#116]
In `ID` there's old phone number that have only 10 digits (in national format excluding country code) .e.g. `0812456789`.

It produces different results compared with [Google Java Version](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) when the input using this format `62812456789`.

![image](https://user-images.githubusercontent.com/5661753/178414003-c36c7792-1eb6-482a-8d0f-0c48ea5658a8.png)

![image](https://user-images.githubusercontent.com/5661753/178414109-1b59d848-412a-49c8-8663-d3daf235c1c1.png)

Thanks.

**Comment by rowanseymour** [comment]
I'm checking Google's Java Demo tho it seems to give the same results as this library https://libphonenumber.appspot.com/phonenumberparser?number=62812345679&country=ID
