### ISSUE TITLE
custom metadata by user?

### ISSUE THREAD

**Issue by okhowang** [nyaruka/phonenumbers#117]
Can I use modified metadata in my App?
metadata in phonenumbers can't be set now

**Comment by rowanseymour** [comment]
It's embedded into the library and I don't see us changing that.

**Comment by okhowang** [comment]
some number rule not exists in embeded metadata,
and I modified locally.
I want use a modified metadata before google fixed rule.

**Comment by rowanseymour** [comment]
Please if you find things in the metadata that need updating, pester google to fix their side, pester us to get the metadata updated here, and then we all benefit.
