### ISSUE TITLE
IsPossibleNumberWithReason() not working properly

### ISSUE THREAD

**Issue by m4rkky** [nyaruka/phonenumbers#12]
You might want to resync with ttacon/libphonenumber
if you call IsPossibleNumberWithReason()
with a number like +1456723456
It returns IS_POSSIBLE when instead it should be TOO_SHORT
IsPossibleNumberWithReason() at ttacon/libphonenumber is using
GetNationalNumberPattern()
Instead of GetPossibleNumberPattern() for the last test.

**Comment by nicpottier** [comment]
Thanks for reporting this, ya, this has drifted. I'm going to rip out the regex creation as previously used and use the same length checks as used by the Java and Python libraries. Will try to get to that in the next week or so, requires some work.
