### ISSUE TITLE
Incorrect national number validation (KZ)

### ISSUE THREAD

**Issue by mayken** [nyaruka/phonenumbers#120]
In Kazakhstan, the phone number starts with +7 (7XX) XXX-XX-XX, but +7 (9XX) XXX XXXX not is Kazakhstan number, how to fix?

Example:
<img width="600" alt="Screen Shot 2022-11-27 at 02 13 48" src="https://user-images.githubusercontent.com/568913/204107634-b05bb551-34aa-4b6a-95a7-73dfeb477d4f.png">

**Comment by rowanseymour** [comment]
We use the metadata from https://github.com/google/libphonenumber and they have it as a valid number https://libphonenumber.appspot.com/phonenumberparser?number=%2B79261234567&country=KZ. So if that's wrong it needs to be fixed there.

**Comment by mayken** [comment]
> We use the metadata from https://github.com/google/libphonenumber and they have it as a valid number https://libphonenumber.appspot.com/phonenumberparser?number=%2B79261234567&country=KZ. So if that's wrong it needs to be fixed there.

Now it works correctly there:
<img width="587" alt="" src="https://user-images.githubusercontent.com/568913/218011716-86ed38f2-fb7a-44e7-af44-4da5054159c0.png">

<img width="577" alt="" src="https://user-images.githubusercontent.com/568913/218011707-5b4400e6-2597-47d5-8290-ff1dc78dfc7f.png">

**Comment by rowanseymour** [comment]
Great, I've updated the metadata we use, and made a new release!
