### ISSUE TITLE
Metadata Issue - AU

### ISSUE THREAD

**Issue by nzhang389** [nyaruka/phonenumbers#121]
We are having issues with phonenumbers with prefix: +61461. This is a new prefix for Telstra Australia. [Google phone number library](https://htmlpreview.github.io/?https://github.com/google/libphonenumber/blob/master/javascript/i18n/phonenumbers/demo-compiled.html) validates the number, but the demo associated with this repository fails. 

Sample number: +61461991234

**Comment by rowanseymour** [comment]
Thanks for the heads up - updated the metadata in https://github.com/nyaruka/phonenumbers/pull/122

**Comment by rowanseymour** [comment]
Does appear our scripts to update https://phonenumbers.temba.io/ are broken so that's even more out of date
