### ISSUE TITLE
explain why the phone number is not valid

### ISSUE THREAD

**Issue by gregwebs** [nyaruka/phonenumbers#125]
The [code explains why a number is not valid](https://github.com/nyaruka/phonenumbers/blob/main/phonenumbers.go#L2126) but IsValidNumber, etc just returns a bool. This information loss makes the library more of a black box. If we had an enumeration of reasons why the number is not valid and got them back along with the false this would allow us to log why a number was not valid. Or alternative a function that returns an `error` that can describe why a number is not valid.

**Comment by rowanseymour** [comment]
The scope of this project is to be a go port of [libphonenumber](https://github.com/google/libphonenumber) so we're following the same API they provide. There is `IsPossibleNumberWithReason` which has some of the same logic and returns an encoded reason such as invalid country code.

**Comment by gregwebs** [comment]
oh, perfect! Sorry I missed it, there's a big interface that is exposed and a lot of code in the phonenumbers.go file. I am wondering if it would help to add it to the usage section of the README or if you don't want to start going down that path?

**Comment by gregwebs** [comment]
Actually, from reading the docs `IsPossibleNumberWithReason` does not do the same amount of validation as `IsValidPhoneNumber` so it doesn't quite meet the needs I opened this issue for.

**Comment by rowanseymour** [comment]
I don't think we want to go down the path of providing docs but maybe we can link to google's own docs. Hopefully one day google provides their own go version!

Re `IsPossibleNumberWithReason`.. I think you could call that first, then `IsValidPhoneNumber` if it returns true, and you'd effectively get a `IsValidNumberWithReason`
