### ISSUE TITLE
ParseNumber is false for number 6580589148 for Country = SG

### ISSUE THREAD

**Issue by XanderDwyl** [nyaruka/phonenumbers#127]
The above number has true value in google libphonenumber.

https://libphonenumber.appspot.com/phonenumberparser?number=6580589148&country=SG

<img width="974" alt="Go_Playground_-_The_Go_Programming_Language" src="https://user-images.githubusercontent.com/5339274/212039587-78f3cd02-625d-48fc-84f1-cc3e55d25ee0.png">

Playground Example:
https://go.dev/play/p/--0DLpblkja

**Comment by rowanseymour** [comment]
Fixed with metadata update
