### ISSUE TITLE
Some prefixes doesn't have country information and is number valid value is coming as false in the newer versions.

### ISSUE THREAD

**Issue by kalyangcp123** [nyaruka/phonenumbers#132]
We are using this library to get the country code and we are checking whether the number is valid or not.

In the older version [v1.1.4](https://github.com/nyaruka/phonenumbers/releases/tag/v1.1.4), these prefixes are coming as valid and getting ISO2 value as well

When we upgraded to the newer version [v1.1.5](https://github.com/nyaruka/phonenumbers/releases/tag/v1.1.5), the same prefixes are coming as invalid.

we would like to know why this is happening. Are these prefixes no longer supported in the newer versions?

**Example Numbers:**

number:+15572003073 
isNumberValid: false
ISO2:

number:+14722023008 
isNumberValid: false 
ISO2:

<img width="1363" alt="Screenshot 2023-02-15 at 12 31 52 PM" src="https://user-images.githubusercontent.com/49232630/218955737-f65760ea-d7c4-4bb3-8ae5-4f0959e5c39f.png">

Note: Even we have tried the latest version as well which is [v1.1.6](https://github.com/nyaruka/phonenumbers/releases/tag/v1.1.6)
Still no luck.

Awaiting your response.

Is there a way we can check which prefixes are valid or not?

**Comment by kalyangcp123** [comment]
Any update on the above one? We are awaiting your response.
This will be very crucial for us

**Comment by rowanseymour** [comment]
Are you seeing the same issue with https://github.com/google/libphonenumber ? This repo is just a port of that library to Go and we use their metadata. So it's important to know if this is a problem in the metadata, or something specific to this port.

**Comment by kalyangcp123** [comment]
hi @rowanseymour ,

I have verified in this as well  https://github.com/google/libphonenumber,  we are seeing the same issue which the number is invalid.

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: null
Result from getNumberType(): UNKNOWN

If you could fix this issue it will be very helpful as well.

We are awaiting your response.

**Comment by rowanseymour** [comment]
If you're seeing the same issue there, then I'm afraid it needs to be fixed there, because we just pull down the metadata from that project.

**Comment by siredwin** [comment]
I am also facing the same problem. My international number comes as invalid even though I am using it now,
