### ISSUE TITLE
Phonenumber details are mismatched in this current phonelib

### ISSUE THREAD

**Issue by kalyangcp123** [nyaruka/phonenumbers#136]
We have observed the one issue which was we are trying to find the wether the phone number is valid or not 
From this link -  https://phonenumbers.temba.io/  --> (nyaruka/phonenumbers)
here the results are coming like this 
{
    "national_number": 5572004088,
    "country_code": 1,
    "is_possible": true,
    **"is_valid": false,**
    "international_formatted": "+1 557-200-4088",
    "national_formatted": "(557) 200-4088"
}

From this link - https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html (google/phonelib)

here the results are coming like this:
 
****Parsing Result:****
{"country_code":1,"national_number":5572004088,"raw_input":"15572004088","country_code_source":10}

****Validation Results:****
Result from isPossibleNumber(): true
**Result from isValidNumber(): true**
Result from isValidNumberForRegion(): true
Phone Number region: US
Result from getNumberType(): FIXED_LINE_OR_MOBILE

Both results are not same between the both phonelibs, because  of this we are getting the wrong results on our code
kindly fix this ASAP.
Awaiting your response.

**Comment by norkans7** [comment]
This should be fixed with the version [v1.1.7](https://github.com/nyaruka/phonenumbers/releases/tag/v1.1.7).

Thanks for reporting that @kalyangcp123
