### ISSUE TITLE
Metadata missing AU numbers

### ISSUE THREAD

**Issue by azhu2** [nyaruka/phonenumbers#141]
google/libphonenumber added Australian (+61) ranges 04937 - 04941 in google/libphonenumber#3026, as indicated on ACMA's [site](https://www.thenumberingsystem.com.au/#!/number-register/search) 
![screenshot-2023-08-08 20 10 07](https://github.com/nyaruka/phonenumbers/assets/2359551/b1e02711-7bd1-466c-9f8f-a6a749071404)

phonenumbers doesn't appear to have this metadata update yet.

**Comment by rowanseymour** [comment]
Seems something has changed in the google repo that is breaking our usual way of grabbing the latest metadata (https://github.com/googlei18n/libphonenumber/trunk/resources/carrier no long works)

**Comment by rowanseymour** [comment]
Nevermind, was just a local svn issue, have updated metadata and released as 1.1.8

**Comment by dhulihan** [comment]
@rowanseymour curiosity question: is there some sort of automation/scraper in place for this project that notifies you when libphonenumber has been changed?

**Comment by rowanseymour** [comment]
Alas not..
