### ISSUE TITLE
Request to update metadata 

### ISSUE THREAD

**Issue by adrianmarshall** [nyaruka/phonenumbers#144]
Hi, 
  I've noticed that the Google library's metadata has been updated a few times in the past few months. This repo is currently out of sync with the Google repo. 
  
  See releases here: https://github.com/google/libphonenumber/releases 
  
  I'm creating this ticket to request a metadata update so that **all new number formats can be validated.** 
  
  thanks,

**Comment by rowanseymour** [comment]
Sorry for the delay - updated now in v1.1.9
