### ISSUE TITLE
Safe Display Name of carriers not implemented

### ISSUE THREAD

**Issue by hemachandran-kalaimani** [nyaruka/phonenumbers#146]
https://github.com/google/libphonenumber has implementation for `PHONE_NUMBER_CARRIER.getSafeDisplayName` in GO not implemented yet.

Is this deliberately not implemented?

**Comment by rowanseymour** [comment]
Unfortunately we don't have the time to maintain a 100% complete port of the Java version and hope one day Google can provide one instead. In the meantime feel free to make a PR.

**Comment by hemachandran-kalaimani** [comment]
@rowanseymour Thanks, created a PR for this.

**Comment by hemachandran-kalaimani** [comment]
Closing this as changes have been merged into main

**Comment by rowanseymour** [comment]
@hemachandran-kalaimani released as 1.2.0 now, thanks!
