### ISSUE TITLE
National Destination Code implementation differs from Java implementation

### ISSUE THREAD

**Issue by hemachandran-kalaimani** [nyaruka/phonenumbers#147]
Implementation of  `getLengthOfNationalDestinationCode` in  https://github.com/google/libphonenumber uses `NON_DIGITS_PATTERN` to split the national significant number, but the GO uses `DIGITS_PATTERN`.

`NON_DIGITS_PATTERN = "(\\D+)"`
`DIGITS_PATTERN = "(\\d+)"`

**Comment by rowanseymour** [comment]
Can you make a PR?

**Comment by hemachandran-kalaimani** [comment]
PR created for this.

**Comment by hemachandran-kalaimani** [comment]
Closing this as changes have been merged into main
