### ISSUE TITLE
Error while installing package

### ISSUE THREAD

**Issue by huberts90** [nyaruka/phonenumbers#15]
Hi,

when I try to install your package I get errors:
Projects/Golang/src/github.com/nyaruka/phonenumbers/phonemetadata.pb.go:108: undefined: proto.InternalMessageInfo
Projects/Golang/src/github.com/nyaruka/phonenumbers/phonemetadata.pb.go:214: undefined: proto.InternalMessageInfo
Projects/Golang/src/github.com/nyaruka/phonenumbers/phonemetadata.pb.go:416: undefined: proto.InternalMessageInfo
Projects/Golang/src/github.com/nyaruka/phonenumbers/phonemetadata.pb.go:676: undefined: proto.InternalMessageInfo
Projects/Golang/src/github.com/nyaruka/phonenumbers/phonenumber.pb.go:173: undefined: proto.InternalMessageInfo

**Comment by nicpottier** [comment]
Can you give me a step by step repro?

**Comment by huberts90** [comment]
The only one step is:
`go get github.com/nyaruka/phonenumbers`

**Comment by nicpottier** [comment]
What version of go? Are you using modules? (outside GO_HOME?)

**Comment by nicpottier** [comment]
Looks like this was a problem in the `go.mod`. Updated in latest version, should be fixed.
