### ISSUE TITLE
Please add new operator code for Turkmenistan

### ISSUE THREAD

**Issue by evgeniy-dammer** [nyaruka/phonenumbers#154]
Hello, please add new 71 code to "Altyn Asyr" operator for Turkmenistan.
https://en.wikipedia.org/wiki/Telephone_numbers_in_Turkmenistan#Mobile_phones

**Comment by rowanseymour** [comment]
We use the metadata from https://github.com/google/libphonenumber so please verify if it is supported there

**Comment by evgeniy-dammer** [comment]
Thank you
