### ISSUE TITLE
Requesting metadata update

### ISSUE THREAD

**Issue by azhu2** [nyaruka/phonenumbers#159]
We've been receiving reports of new Hong Kong numbers +852 595* (activated 2023-09-04 - see changelog on [numbering plan](https://www.ofca.gov.hk/filemanager/ofca/en/content_311/no_plan.pdf)) being rejected. I've confirmed that google/libphonenumber added this in release 8.13.26.

**Comment by rowanseymour** [comment]
Updated metadata and released as v1.3.2
