### ISSUE TITLE
panic: proto: nil destination -- when using phonenumbers.FormatByPattern(..)

### ISSUE THREAD

**Issue by mdouchement** [nyaruka/phonenumbers#16]
Hello,

Thanks for this great port of libphonenumber.

I'm getting a panic error when I'm trying to use the following function:
https://godoc.org/github.com/nyaruka/phonenumbers#FormatByPattern
```
panic: proto: nil destination

goroutine 1 [running]:
github.com/golang/protobuf/proto.Merge(0x131ae60, 0x0, 0x131ae60, 0x13efd00)
	/Users/mdouchement/workspaces/golang/src/github.com/golang/protobuf/proto/clone.go:86 +0x45b
github.com/nyaruka/phonenumbers.FormatByPattern(0xc4202a4c00, 0x0, 0xc4200e1f10, 0x1, 0x1, 0x0, 0x0)
	/Users/mdouchement/workspaces/golang/src/github.com/nyaruka/phonenumbers/phonenumbers.go:1148 +0x196
main.main()
	/Users/mdouchement/workspaces/golang/src/github.com/mdouchementent/testouille/phonenumber.go:28 +0x1da
exit status 2
```

<br>
<br>

According to the stacktrace, the error is raised by the statement `proto.Merge(numFormatCopy, formattingPattern)` because `numFormatCopy` is nil.
https://github.com/nyaruka/phonenumbers/blob/06e7b8a14ab9cb646e98cd7d7f5bbd70679e5ebc/phonenumbers.go#L1143-L1148

<br>
<br>

I'm also wondering if `github.com/golang/protobuf v1.0.0` defined in the `go.mod` is the right version because `proto.InternalMessageInfo` was introduced in the `v.1.1.0` release according to Githubs' history.

**Comment by nicpottier** [comment]
Thanks for the report. Can you give me an exact repro for this? (IE, arguments you are calling this with etc..)

**Comment by nicpottier** [comment]
(latest version has the dependency fix BTW)

**Comment by mdouchement** [comment]
Here is my testing code:
```go
package main

import (
	"fmt"

	"github.com/nyaruka/phonenumbers"
)

var myFormat = phonenumbers.NumberFormat{
	Pattern: stringPtr(`(\d+)`),
	Format:  stringPtr("$1"),
}

func main() {
	number, err := phonenumbers.Parse("+33122334455", "FR")
	if err != nil {
		panic(err)
	}

	f := phonenumbers.FormatByPattern(
		number,
		phonenumbers.E164,
		[]*phonenumbers.NumberFormat{&myFormat},
	)
	fmt.Println(f)
}

func stringPtr(s string) *string {
	return &s
}
```

**Comment by nicpottier** [comment]
Just pushed a fix, let me know if that doesn't address it. Looks like this was a bug that's always been there from the original port so thanks for reporting it.
