### ISSUE TITLE
libphonenumber returning isValidNumber as False for 12-Digit Brazil Number

### ISSUE THREAD

**Issue by narayana-plivo** [nyaruka/phonenumbers#172]
sample number format is
Country Code: 55 (Brazil)
Area Code: 31 (Belo Horizonte)
Subscriber Number: 9862**** (9-digit number starting with 9  mobile number)

**Comment by rowanseymour** [comment]
We use the metadata from Google's library so please verify if it's a problem there https://github.com/googlei18n/libphonenumber
