### ISSUE TITLE
Incorporate code changes to restore area code information for all MX numbers that was lost in v8.13.38

### ISSUE THREAD

**Issue by padjoo** [nyaruka/phonenumbers#173]
libphonenumber code has been updated in v8.13.39 to fix an issue with area code information being lost for MX numbers due to a metadata update in v8.13.38. The code changes are in v8.13.39:
https://github.com/google/libphonenumber/compare/v8.13.39...v8.13.40

Specifically this commit:
https://github.com/google/libphonenumber/commit/3b7ad7eb37943682f059a0ca3dcdf07e5b3077cd

Can Golang code be updated to address this please?

**Comment by rowanseymour** [comment]
We should be able to get this done in the next few weeks, if you need it sooner please make a PR
