### ISSUE TITLE
'buildmetadata' only updates the go source file, running programs cannot be updated

### ISSUE THREAD

**Issue by fulidong-s** [nyaruka/phonenumbers#178]
Hello, I would like to ask if during the execution of "buildmetadata", only the go source file in the gen directory was updated, and the running service is using the map in the buffer, which is also a private property and cannot use the newly generated metadata. Can a hot update be implemented?

**Comment by rowanseymour** [comment]
That sounds beyond the scope of this project, which is just a go port of libphonenumber
