### ISSUE TITLE
PhoneNumberOfflineGeocoder

### ISSUE THREAD

**Issue by xesai** [nyaruka/phonenumbers#18]
Hello, do not find this function, how to get country name, do you plane to add PhoneNumberOfflineGeocoder?

**Comment by nicpottier** [comment]
This isn't what you are looking for?
  https://github.com/nyaruka/phonenumbers/blob/master/phonenumbers_test.go#L1132

**Comment by xesai** [comment]
It does not work right, example: +639103474211, it return nil, but GetRegionCodeForNumber return "PH", GetCountryCode return 63 this is right, so I thought it must return full country name like there https://libphonenumber.appspot.com/phonenumberparser?number=%2B639103474211

**Comment by nicpottier** [comment]
If you just want the country name then you can convert the two letter country code to the country name. That's outside the scope of this library but there are plenty available out there to convert ISO codes to country names in various languages. 

A quick search says here's a few (not recommendations however):
  https://github.com/IftekherSunny/go_country
  https://github.com/pariz/gountries

**Comment by xesai** [comment]
Thank for your answer, that's true, already did that, but does not it must works different way?

**Comment by nicpottier** [comment]
Sorry, not sure I understand the question.

**Comment by xesai** [comment]
I means function there is different between example link above java version (it return full country name) and your golang function

**Comment by nicpottier** [comment]
That's an applet, not a library.
