### ISSUE TITLE
Unexpected parsing of numbers with leading 0's & 1's

### ISSUE THREAD

**Issue by percivalalb** [nyaruka/phonenumbers#185]
Parsing `1112205552637` with the region `US` goes to the valid number `+12205552637`.

This does not match upstream: https://libphonenumber.appspot.com/phonenumberparser?number=1112205552637&country=1

Which produces
> An error occurred while parsing the input: Error type: INVALID_COUNTRY_CODE. Missing or invalid default region. 

I believe this is down to overzealous removal of international exit code digits (0 & 1) and leading zeros. Perhaps this is intentended but I certainly didn't expect the above input to pass.

Example:

```golang
package main

import (
	"fmt"

	"github.com/nyaruka/phonenumbers"
)

func main() {
	pn, err := phonenumbers.Parse("1112205552637", "US")
	if err != nil {
		panic(err)
	}

	fmt.Println(phonenumbers.IsValidNumber(pn), phonenumbers.Format(pn, phonenumbers.E164))
}
```

Outputs:
```
true +12205552637
```

Same for `phonenumbers.Parse("20001012341234", "EG")` which goes to `+201012341234`.

**Comment by rowanseymour** [comment]
Yeah that doesn't seem right. Any chance of a PR to make this library match the Java version ?

**Comment by rowanseymour** [comment]
No wait we're consistent with the upstream library here: https://libphonenumber.appspot.com/phonenumberparser?number=1112205552637&country=US (country is entered as `US` not `1`)

**Comment by percivalalb** [comment]
Oh yeah, `US` not `1`. Okey I'll work around it in my app, I don't want inputs like that parsing!
