### ISSUE TITLE
phonenumbers.Parse Does Not Reject Invalid Input

### ISSUE THREAD

**Issue by hamed21q** [nyaruka/phonenumbers#186]
The phonenumbers.Parse function in the github.com/nyaruka/phonenumbers library does not handle invalid phone numbers containing non-numeric characters properly. For example, providing the input "989null" with the region "IR" does not result in an error but is instead treated as valid.

Steps to Reproduce:

Run the following code:
```go
package main

import (
	"fmt"
	"log"

	"github.com/nyaruka/phonenumbers"
)

func main() {
	_, err := phonenumbers.Parse("989null", "IR")
	if err != nil {
		log.Print(err)
	} else {
		fmt.Println("ok")
	}
}
```

Actual Behavior:
The function does not return an error for the input "989null". It outputs "ok", implying the number is valid.

Expected Behavior:
The function should detect that the input contains invalid characters and return an error indicating the input is not a valid phone number.

Environment:

    Library version: github.com/nyaruka/phonenumbers v1.4.3
      Go version: go1.23.0 linux/amd64
    Operating System: ubuntu 22.0.4

Notes:
This issue suggests that the library's validation mechanism does not properly reject inputs with non-numeric characters. A stricter input validation process might be necessary to address this problem.

Please let me know if more details or test cases are needed.

**Comment by rowanseymour** [comment]
This library is a port of https://github.com/google/libphonenumber and I think we're consistent with how it handles this kind of input https://libphonenumber.appspot.com/phonenumberparser?number=989null&country=IR. It doesn't return an error in this case but instead if you call `IsValidNumber()` on the returned parsed value it will return `false`.
