### ISSUE TITLE
Different Parse Behavior Between Google Java Demo And Golang port

### ISSUE THREAD

**Issue by heyihong** [nyaruka/phonenumbers#2]
Hi, I am trying to use phonenumbers for parsing phone number. When I test phonenumber.Parse("190022+22222", "US"), it returns with no error while in Google Java Demo, it returns NOT_A_NUMBER.

**Comment by nicpottier** [comment]
Hrmm.. so it does. Want to take a shot at a PR for this? `util.go` is a go "port" of the Java class so it should be behaving the same way, but clearly something must be off there.

**Comment by nicpottier** [comment]
Tracked this down to the Java regex defaulting to matching the whole string while golang matches substrings. Altered the affected regexes to have head and toe anchors and added your test case. Thanks for the bug report.

**Comment by heyihong** [comment]
Thanks for the quick fix!
