### ISSUE TITLE
Error during rebuilding metadata

### ISSUE THREAD

**Issue by VadimKulagin** [nyaruka/phonenumbers#20]
Hello!

I moved to the directory with this project and ran the command:
`$GOPATH/bin/buildmetadata`

This command partially completed the work and then gave an error:
```
2019/01/24 20:04:54 Fetching PhoneNumberMetadata.xml from Github
2019/01/24 20:04:56 Building new metadata collection
2019/01/24 20:04:56 Writing new metadata_bin.go
Writing new metadata_bin.go
2019/01/24 20:04:56 Building region map
Writing new countrycode_to_region_bin.go
2019/01/24 20:04:56 Building timezone map
Writing new prefix_to_timezone_bin.go
2019/01/24 20:04:56 Fetching https://github.com/googlei18n/libphonenumber/trunk/resources/carrier from Github
2019/01/24 20:04:56 exit status 1
```

It turns out that the resource requested by the link is not available - error 404.

I think it's worth fixing.

**Comment by nicpottier** [comment]
Looks like link should change to `https://github.com/googlei18n/libphonenumber/tree/master/resources/carrier`. Want to try that and open a PR?

**Comment by VadimKulagin** [comment]
I looked at how `buildmetadata` works. It turned out that this is trying to execute the command:
`svn export https://github.com/googlei18n/libphonenumber/trunk/resources/carrier`

I executed this command manually and received such a strange error:
```
Error validating server certificate for 'https://github.com:443':
 - The certificate is not issued by a trusted authority. Use the
   fingerprint to validate the certificate manually!
Certificate information:
 - Hostname: github.com
 - Valid: from May  8 00:00:00 2018 GMT until Jun  3 12:00:00 2020 GMT
 - Issuer: DigiCert SHA2 Extended Validation Server CA, www.digicert.com, DigiCert Inc, US
 - Fingerprint: CA:06:F5:6B:25:8B:7A:0D:4F:2B:05:47:09:39:47:86:51:15:19:84
(R)eject, accept (t)emporarily or accept (p)ermanently? 
```

After I permanently accepted the certificate, the `buildmetadata` began to work normally.

Sorry for the false alarm :)

**Comment by nicpottier** [comment]
Great. Guessing your build of SVN just doesnt have the root cert authority github uses.
