### ISSUE TITLE
Subversion dependency not stated in README for building metadata

### ISSUE THREAD

**Issue by straticsryan** [nyaruka/phonenumbers#22]
Tried to rebuild meta and got the following results:
```$GOPATH/bin/buildmetadata
2019/03/07 12:41:05 Fetching PhoneNumberMetadata.xml from Github
2019/03/07 12:41:06 Building new metadata collection
2019/03/07 12:41:06 Writing new metadata_bin.go
Writing new metadata_bin.go
2019/03/07 12:41:06 Building region map
Writing new countrycode_to_region_bin.go
2019/03/07 12:41:06 Building timezone map
Writing new prefix_to_timezone_bin.go
2019/03/07 12:41:06 Fetching https://github.com/googlei18n/libphonenumber/trunk/resources/carrier from Github
2019/03/07 12:41:06 exit status 127
```
Fortunately, I knew what 127 meant and looked in the code to see it was making an svn call (of which I didn't have installed on my laptop). Installing subversion resolved the problem.

Anyway, it'd prob be good to note in the README that building the metadata requires subversion installed :)

**Comment by nicpottier** [comment]
Sure, want to update it and submit a PR?

**Comment by nicpottier** [comment]
Added in https://github.com/nyaruka/phonenumbers/commit/5ff4bcd313a6592823d88ed8bd9cd46a7ca554a0
