### ISSUE TITLE
demo not distinguish CA and US area code 

### ISSUE THREAD

**Issue by donginseattle** [nyaruka/phonenumbers#24]
If I input Phone Number:6041234567, Country Code:US, the result is :
"is_possible": true,
    "is_valid": true,

But 604 is BC area code, why demo return wrong info?

**Comment by nicpottier** [comment]
Hrmm. not sure, possible that the metadata needs updating. It does appear that the appspot version is saying possible true, valid false which we should match.

https://libphonenumber.appspot.com/phonenumberparser?number=6041234567&country=US

Will see if I can take a look next week.

**Comment by nicpottier** [comment]
Updated metadata and all seems well now.
