### ISSUE TITLE
Support a Parse method that uses a default country code

### ISSUE THREAD

**Issue by heedson** [nyaruka/phonenumbers#27]
When using the `Parse(numberToParse, defaultRegion)`, I realised a potential need for having the default region be expressed more like a `defaultCode`.

In the example, I want to allow users to select which country code they suspect most of their numbers will use. The reason for displaying to them these values is that it supports:

- non-geo (As I was previously using the `GetSupportedRegions()` to provide a list for them to choose from and this doesn't seem to allow non-geo codes)
- I suspect a user can identify the `+44` over the "GB" code. I know I tried "UK" a few times when starting out.

The result would look something like:

```
stringToParse := "01234567890"
// 800 as an example of non-geo code
num, err := phonenumbers.ParseWithCode(stringToParse, 800)
```

**Comment by nicpottier** [comment]
I wonder if the reason this doesn't exist is ambiguity. For one `+1` covers both the US and Canada.

In general this library tries to follow the same APIs as are available from the main Google library, so perhaps this question is better asked (and likely answered) there? My guess is they would have an answer as to why this isn't a good idea, perhaps due to more complicated ambiguities than the US / Canada one above.

**Comment by heedson** [comment]
Thanks @nicpottier. I understand this follows the other API but wanted to raise it regardless.

I agree with your statement that it technically loses some accuracy but for my example use case, it's all about allowing a user with a set of phone numbers to choose the default parsing code. The region codes work well, to a point, but my concern is the edge case of a user requiring it to parse to `800` by default if receiving a non-specified number.

It's _nearly_ able to support this with the `GetRegionCodeForCountryCode` however that returns "001" for non-geo which is not compatible with the `Parse` method.

I'll check the Google library and see if any issues are similar
Thanks.

**Comment by nicpottier** [comment]
Sounds good. I am curious to hear what the main library says about this, happy to add if they think it is doable but as I said I'm guessing it would be making promises that we couldn't really keep. (and I'm sorry for being so vague about that but I'm just trusting those guys more than myself there)

Feel free to reopen based on what they say.
