### ISSUE TITLE
OffLine Geocoder support

### ISSUE THREAD

**Issue by Matt-Texier** [nyaruka/phonenumbers#29]
Nice golang port of libphonenumber : thanks to make it available as open source.

I was wondering if you ever investigated the support of PhoneNumberOfflineGeocoder in order to get phone number location ?

Thanks Matthieu.

**Comment by nicpottier** [comment]
Have you looked at: https://github.com/nyaruka/phonenumbers/blob/master/phonenumbers.go#L2157

**Comment by Matt-Texier** [comment]
Good catch, I just tested it ... doesn't seems to produce anything more than the country ... for sure it doesn't produce the same result as C++ version of libphonenumber ... 

unless I am missing something, there is no equivalent data as this one : https://github.com/google/libphonenumber/tree/master/resources/geocoding

**Comment by nicpottier** [comment]
Hrmm, it should and I think it is a bug if not, can you share your specific case?

Data is compressed but stored here:
  https://github.com/nyaruka/phonenumbers/blob/master/prefix_to_geocodings_bin.go

Built here:
  https://github.com/nyaruka/phonenumbers/blob/master/cmd/buildmetadata/main.go#L461

Currently tested here:
  https://github.com/nyaruka/phonenumbers/blob/master/phonenumbers_test.go#L1148

So maybe add your test case and open a PR for that issue? Certainly possible there's a bug there.

**Comment by Matt-Texier** [comment]
Thanks, problem solved !

To get the region, you need to use GetGeocodingForNumber function and not the one in this piece of code : https://github.com/nyaruka/phonenumbers/blob/master/phonenumbers.go#L2157

I realized it seeing the CI test you shared with me in your previous message ...

All good, thanks a lot,
Matthieu.

**Comment by nicpottier** [comment]
Ah, ok, apologies, my bad. Also should document those additions since obviously that's not obvious! Thanks.
