### ISSUE TITLE
how to tell if the number is mobile or landline?

### ISSUE THREAD

**Issue by donginseattle** [nyaruka/phonenumbers#31]
If you try text 206-543-2100, reply message says it's a landline. However if try **https://libphonenumber.appspot.com/phonenumberparser?number=2065432100&country=US**, I got FIXED_LINE_OR_MOBILE as Result from getNumberType(). Why can't return  FIXED_LINE?

**Comment by nicpottier** [comment]
This looks correct to me, see test added here:
 https://github.com/nyaruka/phonenumbers/commit/944917882109b3d4b0342ea461e34eb51848c4e6

The parent library also returns `FIXED_LINE_OR_MOBILE`
