### ISSUE TITLE
Unable to identify region for invalid UK number

### ISSUE THREAD

**Issue by quintans** [nyaruka/phonenumbers#34]
doing
<pre>
num, _ := phonenumbers.Parse("+441705673761", "")
region := phonenumbers.GetRegionCodeForNumber(num)
</pre>
`region` will be an empty string
I was expecting `UK`

**Comment by nicpottier** [comment]
From what I can tell this matches the parent library, so we are doing the right thin.

You can test here:
  https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

Guessing that number is not as distinctly UK as you think it is. :)
