### ISSUE TITLE
National Telecommunications Commission of the Philippines has been planning to change the numbering pattern from 7 digits to 8 digits for Manila numbers

### ISSUE THREAD

**Issue by kgajay** [nyaruka/phonenumbers#37]
According to new National Telecommunications Commission of the Philippines, the old 7-digit number will no longer be accessible after 6th Oct 2019. Latest release of phonenumber library still invalidate new number format. Below is example

![Screenshot 2019-09-27 at 1 17 37 PM](https://user-images.githubusercontent.com/10096811/65755433-b56cd880-e130-11e9-8dc2-1995a3c957c0.png)
![Screenshot 2019-09-27 at 1 19 17 PM](https://user-images.githubusercontent.com/10096811/65755434-b56cd880-e130-11e9-86e4-9ab26b25c13f.png)

**Comment by nicpottier** [comment]
You want to file this against the upstream Google project:
  https://github.com/google/libphonenumber/blob/master/FAQ.md

**Comment by kgajay** [comment]
@nicpottier Upstream Google Project has released supporting this feature

https://github.com/nyaruka/phonenumbers/issues/37


But Its still not working in using nyaruka/phonenumbers lib of latest version
