### ISSUE TITLE
ParseToNumber parses valid numbers as invalid

### ISSUE THREAD

**Issue by bharath23** [nyaruka/phonenumbers#38]
When trying to parse a few thousands of numbers we are using ParseToNumber. Unfortunately, we hit a bug which causes ParseToNumber to parse valid phone numbers as invalid. Here is a simple test case that can be used to reproduce the issue. I think for some reason ParseToNumber is not reseting ItalianLeadingZero and NumberOfLeadingZeros which probably is causing the number to be treated as invalid?

Code to reproduce the issue: https://play.golang.org/p/jSsK71K6Mdg

**Comment by bharath23** [comment]
Any idea if this issue will be fixed?

**Comment by nicpottier** [comment]
Apologies, I believe this was fixed in the last release. Are you still encountering it? I can't reproduce it with your code.

**Comment by nicpottier** [comment]
Please have a look at:
  https://github.com/nyaruka/phonenumbers/pull/new/reset-italian-leading-zero

**Comment by nicpottier** [comment]
Closing, fixed in v1.0.52
