### ISSUE TITLE
Unparsing phone number and country code

### ISSUE THREAD

**Issue by ranisalt** [nyaruka/phonenumbers#43]
I am trying to use this library as follows:

1. get user input for phone number (string) and country code (2-char string)
2. use `Parse(phoneNumber, countryCode)` to get a `PhoneNumber`

However from this point I don't have a clue how to handle it, save to database and use it again later on.

I could store `PhoneNumber.CountryCode` and `PhoneNumber.NationalNumber` to database, but this library contains no means of unparsing that back to phone number and country code as input. I could use only number country code IDs as returned by `Parse` but then again this library can't parse using id (int) instead of code (2-char), as far as I could understand.

So how would I parsing a phone number + country code to a "storable" format and then unparse back? I don't care about formatting but I feel uint64 is a horrible choice for storage as it would gobble leading zeros.

**Comment by nicpottier** [comment]
Lots of ways of skinning that cat but we use an E164 formatted string when we store these. IE, `+12065551212`. That is parsable by this library without a country code and has no ambiguity.

You COULD store that as an int64 if you wanted, you'd just have to add in a '+' before passing it to parse to indicate it is E164.

**Comment by hsblhsn** [comment]
> Lots of ways of skinning that cat but we use an E164 formatted string when we store these. IE, `+12065551212`. That is parsable by this library without a country code and has no ambiguity.


Nice, but I can't find the function that takes E164 formatted number and returns `*PhoneNumber`. Can you help me?

**Comment by hsblhsn** [comment]
I am using `phonenumbers.Parse(input, phonenumbers.UNKNOWN_REGION)`. Is this the correct way?
