### ISSUE TITLE
add manual update mechanism

### ISSUE THREAD

**Issue by hanjm** [nyaruka/phonenumbers#44]
When the mobile phone number verification rule xml is updated, my running service needs to run the external cmd program and then recompile and restart before it takes effect.  could you add the Update method to concurrently and securely update? https://github.com/nyaruka/phonenumbers/blob/70effd04591513799241b4403eed392484110901/phonenumbers.go#L3226-L3276

**Comment by nicpottier** [comment]
I don't think this is something I could support adding to this library. There are various options out there to hot swap a service without dropping requests so I would probably suggest looking down those paths.

**Comment by hanjm** [comment]
hi @nicpottier, for a long running phone number validate service which provide HTTP/RPC API, interval auto update phone number validate rule is meaningful, otherwise it needs to periodically  run cmd/buildmetadata/main.go  and recompile and redeploy service. 

here is my WIP fork which add Update function, it works expectedly. https://github.com/hanjm/phonenumbers/tree/dev-add-update

**Comment by nicpottier** [comment]
Glad you found something that works for you! As I said don't plan on merging this into our branch though.
