### ISSUE TITLE
Update metadata

### ISSUE THREAD

**Issue by fpalamour** [nyaruka/phonenumbers#46]
Hi,
When can we expect the new release with updated metadata ?
see : https://github.com/google/libphonenumber/pull/2414
Thank you.

**Comment by nicpottier** [comment]
We generally push updates a few days after the official release is made.

**Comment by fpalamour** [comment]
Alright no worries. Thanks for your reply.

**Comment by fpalamour** [comment]
I'm sorry to put some pressure on you but I'd be so glad if the update for the 8.11 release was eventually done in the near future.
Cheers.

**Comment by nicpottier** [comment]
Just released v1.0.54 which should have those.

**Comment by fpalamour** [comment]
Thank you for the release. Unfortunately, I've just realised that google didn't update the metadata for Gabon (GA) correctly as my valid numbers are still parsed as invalid (too long). I guess I'll have to wait some more.

Cheers.
