### ISSUE TITLE
Corner case with French overseas territory ? 

### ISSUE THREAD

**Issue by Matt-Texier** [nyaruka/phonenumbers#53]
Hi Guys,

Could be that I found a corner case that I would like to share with you. I am using your implementation for a telco ticketing system . This telco is exchanging lots of calls from and to the French Overseas territories.

I do have issues with the result of GetGeocodingForNumber.

Here is example which hopefully will make the case clear ...

I have a called number with its national representation like this : 590555008,
Its e164 representation looks like this : +590590555008

When used like this and passing +590590555008 as parameter
```go
func libPhoneNumberEnrichFields(myNumber string) (string, string, string, string) {
	var num *phonenumbers.PhoneNumber
	var err error
	var geo string
	num, err = phonenumbers.Parse(myNumber, "FR")
	if err != nil {
		global.Logger.WithFields(logrus.Fields{
			"error": err,
			"number": myNumber,
		}).Info("unable to parse number")
		return "", "", "", ""
	}

	geo, err = phonenumbers.GetGeocodingForNumber(num, "fr")
	if err != nil {
		global.Logger.WithFields(logrus.Fields{
			"error": err,
			"number": myNumber,
		}).Info("unable to GeoCode this number")
		return "", "", "", ""
	}
	cc := strconv.Itoa(int(num.GetCountryCode()))
	country := phonenumbers.GetRegionCodeForNumber(num)
	numType := descNumTypeFromType[phonenumbers.GetNumberType(num)]
	return cc, country, geo, numType
}
```

GetGeocodingForNumber is returning me an empty string wo generating any errors.

However, when you go to ITU web site and open this page: 
https://www.itu.int/oth/T020200004B/en
Then in the pdf format file and click on the link that gives the xls file called MAJNUM.xls:

https://extranet.arcep.fr/portail/LinkClick.aspx?fileticket=PBA1WK-wnOU%3d&tabid=217&portalid=0&mid=850

You search for phone number range 059055, you will find the region/location. It should be the location of "Basse-Terre".

Could you please help me to investigate where is the problem ?

Is it an ITU data base problem or could it be that I don't use you library properly ?

I took this example but it seems to apply to all those territories : Guadeloupe, Martinique, Reunion... It applies to all those country codes +262, +590, +594, +596. 

If you could have a look it would be fantastic !

Thanks Matthieu.

**Comment by Matt-Texier** [comment]
Hi Guys,

A bit more testing and investigations give me the following explanation:

When giving, for example, this number to the libphonenumber: +590590240963 (e164)

I do have:
- country code : GP (Guadeloupe correct),
- location : "" (empty incorrect),
- type : fixed ligne (correct),

Now if I give +33590240963 or 590240963, 

I do have:
- country code : FR (which is half correct, Guadeloupe belongs to France but have its own CC)
- Location :  Morne-À-l'Eau (correct location in Guadeloupe)
- type : fixed line (correct).

I saw that in your code, you convert national representation of the number back to e164 before searching into location index. I guess you did it for very good reasons but it seems to create an issue here ... 

https://github.com/nyaruka/phonenumbers/blob/8ab2b54b05ef7ba0ab5249455449e8306a6df9b4/phonenumbers.go#L3336

Could you please tell me if that sounds as a fixable situation or I need to run the function two times and mix informations ?

Thanks Matt.

**Comment by nicpottier** [comment]
Hi Matt.
Have you played around with the Java version of this library that is upstream of us? This is a port of sorts of that (official Google) one and we try to keep our behavior the same as it. So would be great to verify that we are doing something different than them.

**Comment by Matt-Texier** [comment]
Hi Nic (I guess that' your first name :-)),

I checked against a web site which is, most probably, using java code of libphonenumber behind the scene. Result is similar which is probably a good news for you but not for me :-).

Two points:

* I wonder if you and libphonenumber is using the most up to date phone number allocation file :  https://extranet.arcep.fr/portail/LinkClick.aspx?fileticket=PBA1WK-wnOU%3d&tabid=217&portalid=0&mid=850

* I don't get why using the e164 representation of the number rather than it nation representation. I not super familiar with standardisation rules and organisation for telephony but a pragmatic approach would be to use national representation for everything which is local/region and e164 for everything related to international (country code etc ...).

Could you please point me to the ITU file you use to build you local/region index ? I tried to download it from the code ... no joy ... I would like to check that data you rely on is the same as the one I found on ITU myself (pointing to the French regulator : ARCEP).

Thanks Matt.

**Comment by nicpottier** [comment]
Salut Matt!

You are probably going to get a better answer to this type of question from the main phonenumbers peeps:
  https://github.com/google/libphonenumber/blob/master/CONTRIBUTING.md

They are the ones that control the metadata and general approach, this is just a port and we try to stay consistent with them.

**Comment by nicpottier** [comment]
Closing as this is a metadata bug that needs to be fixed upstream of us.
