### ISSUE TITLE
Cannot pass Null to prefix while parsing a number

### ISSUE THREAD

**Issue by itsursujit** [nyaruka/phonenumbers#54]
For the numbers starting with plus `+`, I am not being be able to pass null or nothing for the 2nd parameter of Parse method as in:

```
num, err := phonenumbers.Parse("6502530000", "US")
```
This would be invalid

But 
I can't do something like this:
```
num, err := phonenumbers.Parse("+6502530000")
```
This should be valid enough, How can I pass Null value or nothing for prefix when there's plus symbol or 00

**Comment by nicpottier** [comment]
Can't you pass empty string?
