### ISSUE TITLE
getNameForValidNumber not found

### ISSUE THREAD

**Issue by rif** [nyaruka/phonenumbers#6]
Is there another method to get the carrier name for a valid phone number?

https://github.com/nyaruka/libphonenumber/blob/master/java/carrier/src/com/google/i18n/phonenumbers/PhoneNumberToCarrierMapper.java#L73

**Comment by nicpottier** [comment]
This isn't ported over as of yet. PR welcome though.

**Comment by rif** [comment]
Just saw this PR isn't that about the same issue. What is the status about that one?

**Comment by nicpottier** [comment]
Looks like it just needs a bit of TLC to get over the finish line.

**Comment by nicpottier** [comment]
Now found in: https://github.com/nyaruka/phonenumbers/blob/master/phonenumbers.go#L3366
