### ISSUE TITLE
Allocates a large chunk of memory at run time

### ISSUE THREAD

**Issue by nathan-fiscaletti** [nyaruka/phonenumbers#62]
This library seems to statically allocate a LOT of data at run time. Nearly 3MB of it. On some devices that have severe memory limitations, this can be an issue. 

I've put together a small python script that can demonstrate the memory footprint that the library can bring with it.

<details>
  <summary>The python script</summary>
  
  ```python
  import psutil
  import os
  import subprocess
  import time

  GO_SCRIPT_WITH_PHONENUMBERS = """
  package main

  import (
      "github.com/nyaruka/phonenumbers"
      "time"
  )

  func main() {
      // We have to USE the library if we import it, so here is what
      // should be a simple invocation.
      phonenumbers.NormalizeDigitsOnly("1234567890")

      // Keep the process alive
      for true {
          time.Sleep(1)
      }
  }
  """

  GO_SCRIPT_WITHOUT_PHONENUMBERS = """
  package main

  import (
      "time"
  )

  func main() {
      // Keep the process alive
      for true {
          time.Sleep(1)
      }
  }
  """

  def run_go_process(with_phonenumbers):
      with open("tmp_go_script.go", 'w') as f:
          if with_phonenumbers:
              f.write(GO_SCRIPT_WITH_PHONENUMBERS)
          else:
              f.write(GO_SCRIPT_WITHOUT_PHONENUMBERS)
      os.system("go build -o tmp_go_binary tmp_go_script.go")
      process = subprocess.Popen("./tmp_go_binary", shell=False)
      time.sleep(1)
      psproc = psutil.Process(process.pid)
      return psproc.memory_full_info().uss

  def sizeof_fmt(num, suffix='', kunit=1024.0):
      for unit in ['','K','M','G','T','P','E','Z']:
          if abs(num) < kunit:
              return "%3.2f%s%s" % (num, unit, suffix)
          num /= kunit
      return "%.1f%s%s" % (num, 'Y', suffix)

  def main():
      with_phonenumbers = run_go_process(with_phonenumbers=True)
      without_phonenumbers = run_go_process(with_phonenumbers=False)
      print(f"With Phonenumbers:    {sizeof_fmt(with_phonenumbers)}")
      print(f"Without Phonenumbers: {sizeof_fmt(without_phonenumbers)}")

  if __name__ == "__main__":
      main()
  ```
  
</details>

This script will create two Go binaries, one that includes the phonenumbers library and one that does not. Once each process is spun up, it will use the `psutil` python library to retrieve the current memory footprint of the binary. The process will have 1s to settle before this sample is taken. The value displayed is the amount of memory that would be freed up if the process were to be terminated immediately.

> It's important that the script is run as root as it uses the [`.memory_full_info()`](https://psutil.readthedocs.io/en/latest/#psutil.Process.memory_full_info) function of the `psutil` Python library.

When I run this script on my macOS 10.15.5 system running go 1.13, this is the output I see:
```
$ python3 phonenumbers_memory.py
With Phonenumbers:    3.02M
Without Phonenumbers: 716.00K
```

That's quite a drastic increase when including the library. Now, it's not clear at this time if this is due to deeper dependencies of the phonenumbers library or if it's due to the number of static allocations in the library ( I would assume for mapping phone number formats / ISO codes / etc.) However, it seems pretty excessive.

**Comment by nicpottier** [comment]
Ya, I mean there's a whole database of phone numbers, locations, timezones etc, all embedded in the library, so no great surprise there. There could probably be approaches explored where you try to use external assets for this instead of having those embedded as code but that's not a goal of this particular library, so going to close this as "as designed".
