### ISSUE TITLE
'abcde10' is a US phone number?

### ISSUE THREAD

**Issue by or-else** [nyaruka/phonenumbers#64]
https://play.golang.org/p/5L3Bj6ePfso

```
package main

import (
	"fmt"

	"github.com/nyaruka/phonenumbers"
)

func main() {
	num, err := phonenumbers.Parse("abcde10", "US")
	fmt.Println("Number:", num, err)
}
```

`Number: country_code:1 national_number:10  <nil>`

**Comment by or-else** [comment]
I looked at the code and it seems to be a misfeature rather than a bug. `Parse` attempts to interpret any string as a phone number. Any string with a numeric suffix will be interpreted as a phone number which seems wrong but probably intentional behavior.

Can you expose `isViablePhoneNumber` so the string can be tested before parsing?

**Comment by or-else** [comment]
BTW, you may want to run a linter on your code.

**Comment by nicpottier** [comment]
Take a look at `IsPossibleNumber` and `IsValidNumber`, guessing that is what you want to use.

The API for this library mostly just tries to match what the official upstream google/java version does.

**Comment by or-else** [comment]
Both `IsPossibleNumber` and `IsValidNumber` require parsing the number: "abcdef6505551212" is not a valid phone number, but `Parse("abcdef6505551212", "US")` will return a `PhoneNumber` which will be tested as valid by both `IsPossibleNumber` and `IsValidNumber`. 

> The API for this library mostly just tries to match

This is not a very good reason to keep problematic code.

**Comment by nicpottier** [comment]
This is the same behavior as the official library:
  https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

The goal of this library is to behave the same as upstream. If you don't agree with that then by all means I encourage you to fork this and adapt as you see fit, I'll be the first to recommend it if it works well!
