### ISSUE TITLE
recently added number prefix not validate properly.

### ISSUE THREAD

**Issue by Yahampath** [nyaruka/phonenumbers#65]
Hi,

for the "LK", they added a "074" number prefix a few days ago. but it's not recognized by the library. I tried to build the dataset and still not recognized. But in the Java library, it's recognized as expected. even on an online page.

```Go
        num, err := phonenumbers.Parse("746557816", "LK")
	if err != nil {
		log.Fatal(err)
	}

	fmt.Println(phonenumbers.IsValidNumber(num))
```

**Comment by nicpottier** [comment]
Perhaps you didn't have the latest metadata? Added a test and I believe this is doing the right thing with the latest release:
  https://github.com/nyaruka/phonenumbers/blob/master/phonenumbers_test.go#L1298
