### ISSUE TITLE
GB/UK ( United Kindom ) not present in prefix_to_geocoding_bin.go

### ISSUE THREAD

**Issue by TeoV** [nyaruka/phonenumbers#66]
Hi all,

First of all thanks for this awesome library.
I did some tests today and found out that GB/UK is missing from prefix_to_geocoding_bin.go
Tried to add it manually by myself but didn't succeed ( found this https://www.itu.int/oth/T02020000DD/en but don't know exactly how to add it )
Can you please describe the steps of adding support for a prefix?

Thanks,
TeoV

**Comment by nicpottier** [comment]
So the prefix to geocoding is built off of the data from the official Google upstream project:
  https://github.com/google/libphonenumber/tree/master/resources/geocoding

I imagine if it doesn't exist there then there is likely a good reason. You may want to follow up with them on that.

**Comment by nicpottier** [comment]
Closing, this is upstream data.
