### ISSUE TITLE
Question - Is Ivory Coast new number format supported?

### ISSUE THREAD

**Issue by vladcll** [nyaruka/phonenumbers#76]
Ivory Coast (Côte D'Ivoire - CI) will switch from 8 to 10 digits format at the midnight between 30th - 31st of January, 2021. Is the new format supported by this library?

Below the Google translated version of https://www.artci.ci/index.php/foire-aux-questions/470-nouveau-plan-de-national-de-numeroration.html - 6th question.

> As of January 31, 2021 at 12:00 a.m. 8-digit numbers will no longer work.
> The principle of tilting is very simple.
> The general principle of switching is to add a prefix in front of the old 8-digit numbers.
> We based ourselves on so-called “characteristic” figures of operators that the population already recognizes.
> So for mobile numbers, add:
> 
> - " 07 " in front of the old numbers of ORANGE
> - " 05 " in front of the old ones of MTN
> - " 01 " in front of those of MOOV
> 
> For fixed numbers, you must add:
> 
> - " 27 " in front of the old numbers of ORANGE
> - " 25 " in front of the old ones of MTN
> - " 21 " in front of those of MOOV.

Thank you!

**Comment by nicpottier** [comment]
Hi @vladcll .. the metadata for this library is maintained / created by the upstream google library. I am sure this is on their radar, but if you want a definitive answer I would check there:
  https://github.com/google/libphonenumber

We generally update the metadata on this library fairly quickly after they make changes.

**Comment by yeuhk** [comment]
Hi @nicpottier I see the google library has been updated with the new Ivory Coast formats earlier today, is there an eta of when this library will be updated?  Thanks.
