### ISSUE TITLE
Philippine mobile phone number verification failed

### ISSUE THREAD

**Issue by GoJaden** [nyaruka/phonenumbers#78]
+6309638167412 
This is a Philippine mobile phone number, but it cannot be verified correctly. Can fix it?

**Comment by cristaloleg** [comment]
Hi, what do you mean by "verified correctly" ?

**Comment by GoJaden** [comment]
> Hi, what do you mean by "verified correctly" ?

Incorrect verification of Philippine mobile phone number in version 59。。
In the latest version, I found that it can be verified correctly. Sorry to disturb you

**Comment by cristaloleg** [comment]
No problem, happy that recent versions work fine.
