### ISSUE TITLE
Phone number validation failed

### ISSUE THREAD

**Issue by vasundhara785** [nyaruka/phonenumbers#79]
Hi,

Tried with a sweden dummy number  +461111111.
This turned out to be a valid number.

Thanks.

**Comment by cristaloleg** [comment]
Hi, any details? What funcs do you use? Have you checked it against previous version? What about this page? Does it work here? https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html Thanks!

**Comment by vasundhara785** [comment]
Used the below method :    
        num, err := phonenumbers.Parse("+461111111", "IN")
        **phonenumbers.IsValidNumber(num)**

The highlighted one returned true.
I have git clone from this page the latest version.

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
Here also it says valid number

**Comment by cristaloleg** [comment]
Regarding this page:

```
Result from isValidNumberForRegion(): false
```

Cause `IN` isn't a Sweden country code.

**Comment by vasundhara785** [comment]
num, err := phonenumbers.Parse("+461111111", "IN")
phonenumbers.IsValidNumber(num)

**_IN_** used here is for default when + or 00  is not given as prefix to the number.

num, err := phonenumbers.Parse("+461111111", "SE")
phonenumbers.IsValidNumber(num)

Also,Even in the above function **_SE_** is used as region code it gives as valid number.


Please try to look into the sample code attached.
https://play.golang.org/p/nCPu3w-mNuc

**Comment by quasilyte** [comment]
@vasundhara785 could you please re-phrase it a little bit, it's not easy to understand what needs to be fixed. Maybe try a different approach?

What about a Go test that fails, but it should pass? When there will be a fix, it can be checked against that test.
The most helpful way is to send a PR with that test, I think, but you can post your code here if you don't want to open a PR.

**Comment by vasundhara785** [comment]
@quasilyte  Could you please look into the code attached.
https://play.golang.org/p/nCPu3w-mNuc

The number provided in the example is not valid but the library says its valid.

**Comment by vonmutinda** [comment]
Cannot validate Nigerian numbers correctly in `v.1.0.61`.

https://play.golang.org/p/I76HGKRGPKG

**Comment by vasundhara785** [comment]
How to differentiate between singapore numbers (65XXXXXXXX) and india numbers with (65XXXXXXXX)?

**Comment by nicpottier** [comment]
@vasundhara785 You are parsing a full E164 number, which is valid. The library is deriving the correct region code at that point and sets it on the number passed back. That is always `SE`.. you are then testing against that and that is correctly always true.

If you actually passed in `IN` to your test for `isValidNumberForRegion` you would correctly get `false`
