### ISSUE TITLE
export isNumberMatchWithNumbers

### ISSUE THREAD

**Issue by akurth** [nyaruka/phonenumbers#81]
Would it be possible to export `isNumberMatchWithNumbers(firstNumberIn, secondNumberIn *PhoneNumber) MatchType`?

In libphonenumber (Java), the corresponding method is public, while here only `IsNumberMatch(firstNumber, secondNumber string) MatchType` is exported. This makes it impossible to pass default regions to the function, and thus the result behaves differently from the Java version.

Example:
PhoneNumber "0049 721 12345" compared to "+49 721 12345" results in EXACT_MATCH when default region "DE" is given.
String "0049 721 12345" compared to "+49 721 12345" results in NSN_MATCH.

**Comment by nicpottier** [comment]
Yes, totally, this is likely just an oversight due to Go's unique way of determining what is public. :)

**Comment by nicpottier** [comment]
Do you mind putting together a PR with some test cases?
