### ISSUE TITLE
Validation for IN failed

### ISSUE THREAD

**Issue by vasundhara785** [nyaruka/phonenumbers#82]
Hi,

Given a sample number 1234567890 with region as IN.
`func IsValidNumber returns true.`
Is  1234567890 a valid phone number for india??
Please look at the code attached.
https://play.golang.org/p/KomI-BW1zMr

**Comment by nicpottier** [comment]
Seems so!

Please  test against upstream before opening issues:
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html
