### ISSUE TITLE
Get Area Code/Prefix

### ISSUE THREAD

**Issue by RaMin0** [nyaruka/phonenumbers#87]
[`GetCarrierForNumber`](https://github.com/nyaruka/phonenumbers/blob/116976019396e7a403119fd04385a45c49e95e9f/phonenumbers.go#L3389) tries to guess the name of the carrier of a given number. In its implementation, it calls [`getValueForNumber`](https://github.com/nyaruka/phonenumbers/blob/116976019396e7a403119fd04385a45c49e95e9f/phonenumbers.go#L3348) which [in turn](https://github.com/nyaruka/phonenumbers/blob/116976019396e7a403119fd04385a45c49e95e9f/phonenumbers.go#L3375-L3383) attempts to find the "prefix" (or [`index`](https://github.com/nyaruka/phonenumbers/blob/116976019396e7a403119fd04385a45c49e95e9f/phonenumbers.go#L3376)) of the provided number that exists in [`carrierMapData`](https://github.com/nyaruka/phonenumbers/blob/116976019396e7a403119fd04385a45c49e95e9f/prefix_to_carriers_bin.go#L3).

My question is, is it possible to alter the function to add this "prefix" as an extra return value? It's a requirement in a project I'm working on where the prefix is needed rather than the carrier name. For example:

```go
func getValueForNumber(...) (string, int, error) { // int is for the prefix/index
```

~I'm happy to create a PR for it if this looks like a good addition to this package.~ I went ahead and created [one](https://github.com/nyaruka/phonenumbers/pull/88).

**Comment by RaMin0** [comment]
@nicpottier Let's close this?

**Comment by nicpottier** [comment]
Yep, added in https://github.com/nyaruka/phonenumbers/pull/88, thank you!
