### ISSUE TITLE
unexpected parse behavior

### ISSUE THREAD

**Issue by zhqu1148980644** [nyaruka/phonenumbers#95]
```go
ph, err := phonenumbers.Parse("4163020541", "CN")
```

This code raises no error, though it's obviously not a chinese phone number.

**Comment by nicpottier** [comment]
Parsing doesn't validate (this is the case with all the APIs upstream as well). 

After parsing you want to call `IsPossibleNumber` or `IsValidNumber`

**Comment by zhqu1148980644** [comment]
@nicpottier `IsValidNumber` also returns `true`.

![image](https://user-images.githubusercontent.com/29366130/124852234-99b98600-dfd6-11eb-9ab9-40f67b5593ee.png)

**Comment by rowanseymour** [comment]
According to the upstream library that is correct https://libphonenumber.appspot.com/phonenumberparser?number=4163020541&country=CN. If you believe that is incorrect you should open an issue on https://github.com/google/libphonenumber.

**Comment by zhqu1148980644** [comment]
> According to the upstream library that is correct https://libphonenumber.appspot.com/phonenumberparser?number=4163020541&country=CN. If you believe that is incorrect you should open an issue on https://github.com/google/libphonenumber.

get it. thanks for your reply.
